using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

// Token: 0x02000A39 RID: 2617
[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[DebuggerNonUserCode]
[CompilerGenerated]
internal class FormatAndOut_format_xxx
{
	// Token: 0x0600683E RID: 26686 RVA: 0x0021194C File Offset: 0x0020FB4C
	internal FormatAndOut_format_xxx()
	{
	}

	// Token: 0x17001C7B RID: 7291
	// (get) Token: 0x0600683F RID: 26687 RVA: 0x00211954 File Offset: 0x0020FB54
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	internal static ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(FormatAndOut_format_xxx.resourceMan, null))
			{
				ResourceManager resourceManager = new ResourceManager("FormatAndOut_format_xxx", typeof(FormatAndOut_format_xxx).Assembly);
				FormatAndOut_format_xxx.resourceMan = resourceManager;
			}
			return FormatAndOut_format_xxx.resourceMan;
		}
	}

	// Token: 0x17001C7C RID: 7292
	// (get) Token: 0x06006840 RID: 26688 RVA: 0x00211993 File Offset: 0x0020FB93
	// (set) Token: 0x06006841 RID: 26689 RVA: 0x0021199A File Offset: 0x0020FB9A
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	internal static CultureInfo Culture
	{
		get
		{
			return FormatAndOut_format_xxx.resourceCulture;
		}
		set
		{
			FormatAndOut_format_xxx.resourceCulture = value;
		}
	}

	// Token: 0x17001C7D RID: 7293
	// (get) Token: 0x06006842 RID: 26690 RVA: 0x002119A2 File Offset: 0x0020FBA2
	internal static string CannotSpecifyAutosizeAndColumnsError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("CannotSpecifyAutosizeAndColumnsError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C7E RID: 7294
	// (get) Token: 0x06006843 RID: 26691 RVA: 0x002119B8 File Offset: 0x0020FBB8
	internal static string CannotSpecifyViewAndPropertyError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("CannotSpecifyViewAndPropertyError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C7F RID: 7295
	// (get) Token: 0x06006844 RID: 26692 RVA: 0x002119CE File Offset: 0x0020FBCE
	internal static string FOD_ClassIdInvalid
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FOD_ClassIdInvalid", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C80 RID: 7296
	// (get) Token: 0x06006845 RID: 26693 RVA: 0x002119E4 File Offset: 0x0020FBE4
	internal static string FOD_InvalidClassid
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FOD_InvalidClassid", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C81 RID: 7297
	// (get) Token: 0x06006846 RID: 26694 RVA: 0x002119FA File Offset: 0x0020FBFA
	internal static string FOD_InvalidClassidProperty
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FOD_InvalidClassidProperty", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C82 RID: 7298
	// (get) Token: 0x06006847 RID: 26695 RVA: 0x00211A10 File Offset: 0x0020FC10
	internal static string FOD_InvalidPropertyType
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FOD_InvalidPropertyType", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C83 RID: 7299
	// (get) Token: 0x06006848 RID: 26696 RVA: 0x00211A26 File Offset: 0x0020FC26
	internal static string FOD_NullDataMember
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FOD_NullDataMember", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C84 RID: 7300
	// (get) Token: 0x06006849 RID: 26697 RVA: 0x00211A3C File Offset: 0x0020FC3C
	internal static string FOD_RecursiveProperty
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FOD_RecursiveProperty", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C85 RID: 7301
	// (get) Token: 0x0600684A RID: 26698 RVA: 0x00211A52 File Offset: 0x0020FC52
	internal static string FormattingError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("FormattingError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C86 RID: 7302
	// (get) Token: 0x0600684B RID: 26699 RVA: 0x00211A68 File Offset: 0x0020FC68
	internal static string GroupStartDataIndentedAutoGeneratedLabel
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("GroupStartDataIndentedAutoGeneratedLabel", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C87 RID: 7303
	// (get) Token: 0x0600684C RID: 26700 RVA: 0x00211A7E File Offset: 0x0020FC7E
	internal static string IEnum_Header
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("IEnum_Header", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C88 RID: 7304
	// (get) Token: 0x0600684D RID: 26701 RVA: 0x00211A94 File Offset: 0x0020FC94
	internal static string IEnum_ManyObjects
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("IEnum_ManyObjects", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C89 RID: 7305
	// (get) Token: 0x0600684E RID: 26702 RVA: 0x00211AAA File Offset: 0x0020FCAA
	internal static string IEnum_NoObjects
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("IEnum_NoObjects", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C8A RID: 7306
	// (get) Token: 0x0600684F RID: 26703 RVA: 0x00211AC0 File Offset: 0x0020FCC0
	internal static string IEnum_OneObject
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("IEnum_OneObject", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C8B RID: 7307
	// (get) Token: 0x06006850 RID: 26704 RVA: 0x00211AD6 File Offset: 0x0020FCD6
	internal static string InvalidViewNameError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("InvalidViewNameError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C8C RID: 7308
	// (get) Token: 0x06006851 RID: 26705 RVA: 0x00211AEC File Offset: 0x0020FCEC
	internal static string MshExpressionError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("MshExpressionError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C8D RID: 7309
	// (get) Token: 0x06006852 RID: 26706 RVA: 0x00211B02 File Offset: 0x0020FD02
	internal static string NonExistingViewNameError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("NonExistingViewNameError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C8E RID: 7310
	// (get) Token: 0x06006853 RID: 26707 RVA: 0x00211B18 File Offset: 0x0020FD18
	internal static string SuggestValidViewNamePrefix
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("SuggestValidViewNamePrefix", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C8F RID: 7311
	// (get) Token: 0x06006854 RID: 26708 RVA: 0x00211B2E File Offset: 0x0020FD2E
	internal static string UnknownViewNameError
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("UnknownViewNameError", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x17001C90 RID: 7312
	// (get) Token: 0x06006855 RID: 26709 RVA: 0x00211B44 File Offset: 0x0020FD44
	internal static string UnknownViewNameErrorSuffix
	{
		get
		{
			return FormatAndOut_format_xxx.ResourceManager.GetString("UnknownViewNameErrorSuffix", FormatAndOut_format_xxx.resourceCulture);
		}
	}

	// Token: 0x04003269 RID: 12905
	private static ResourceManager resourceMan;

	// Token: 0x0400326A RID: 12906
	private static CultureInfo resourceCulture;
}
